### ISSUE TITLE
hi，IPC=50，why your syn image has a size of [200,3,32,32]?why 200

### ISSUE THREAD

**Issue by Luo-Zhongwei** [Hansong-Zhang/DANCE#3]
#img_syn[200,3,32,32] ? ipc=50 ,so syn img just 50 ,why 200
            img_syn, _ = synset.sample(c, max_size=args.batch_syn_max)
            ts.stamp("data")

            with torch.no_grad():
                for i in range(0,128):  
                    visualize_image(i,img,"ori_img")
                for j in range(0,200):  
                    visualize_image(j,img_syn,"syn_img")

**Comment by Hansong-Zhang** [comment]
Hi zhongwei,

Sorry for the delayed reply, i just came back from Jeju for IJCAI yesterday.
The synthetic images have a size of 200 (50 * 4) because the factor technique is adopted in DANCE, take CIFAR as an example, an image is first downsampled to 16*16 in condensing process and then upsampled to the original size in training stage.

If there is any other questions, feel free to let me know.

Best regards,
Hansong

**Comment by Hansong-Zhang** [comment]
> #img_syn[200,3,32,32] ? ipc=50 ,so syn img just 50 ,why 200 img_syn, _ = synset.sample(c, max_size=args.batch_syn_max) ts.stamp("data")
> 
> ```
>         with torch.no_grad():
>             for i in range(0,128):  
>                 visualize_image(i,img,"ori_img")
>             for j in range(0,200):  
>                 visualize_image(j,img_syn,"syn_img")
> ```

Hi zhongwei,

Sorry for the delayed reply, i just came back from Jeju for IJCAI yesterday.
The synthetic images have a size of 200 (50 * 4) because the factor technique is adopted in DANCE, take CIFAR as an example, an image is first downsampled to 16*16 in condensing process and then upsampled to the original size in training stage.

If there is any other questions, feel free to let me know.

Best regards,
Hansong
